name: 'Test table_of_content'

on:
  push:
    paths:
      - 'practice/basics/table_of_contents.py'
      - '.github/workflows/table_of_contents.yaml'
  workflow_dispatch:

jobs:
  test-table-of-content:
    timeout-minutes: 1
    name: 'test-table-of-content'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: practice
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
      - run: |
          pytest practice/basics/table_of_contents_test.py
